// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: functional/v1/complex.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_HIGH        Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_HIGH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_HIGH":        2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_functional_v1_complex_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_functional_v1_complex_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_functional_v1_complex_proto_rawDescGZIP(), []int{0}
}

type ComplexMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexMetadata) Reset() {
	*x = ComplexMetadata{}
	mi := &file_functional_v1_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMetadata) ProtoMessage() {}

func (x *ComplexMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMetadata.ProtoReflect.Descriptor instead.
func (*ComplexMetadata) Descriptor() ([]byte, []int) {
	return file_functional_v1_complex_proto_rawDescGZIP(), []int{0}
}

func (x *ComplexMetadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ComplexMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ComplexTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *ComplexMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexTarget) Reset() {
	*x = ComplexTarget{}
	mi := &file_functional_v1_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexTarget) ProtoMessage() {}

func (x *ComplexTarget) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexTarget.ProtoReflect.Descriptor instead.
func (*ComplexTarget) Descriptor() ([]byte, []int) {
	return file_functional_v1_complex_proto_rawDescGZIP(), []int{1}
}

func (x *ComplexTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComplexTarget) GetMetadata() *ComplexMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ComplexRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Priority      Priority                    `protobuf:"varint,1,opt,name=priority,proto3,enum=functional.v1.Priority" json:"priority,omitempty"`
	Metadata      *ComplexMetadata            `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Targets       []*ComplexTarget            `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	TargetByKey   map[string]*ComplexTarget   `protobuf:"bytes,4,rep,name=target_by_key,json=targetByKey,proto3" json:"target_by_key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MetadataByKey map[string]*ComplexMetadata `protobuf:"bytes,5,rep,name=metadata_by_key,json=metadataByKey,proto3" json:"metadata_by_key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priorities    []Priority                  `protobuf:"varint,6,rep,packed,name=priorities,proto3,enum=functional.v1.Priority" json:"priorities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexRequest) Reset() {
	*x = ComplexRequest{}
	mi := &file_functional_v1_complex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexRequest) ProtoMessage() {}

func (x *ComplexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_complex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexRequest.ProtoReflect.Descriptor instead.
func (*ComplexRequest) Descriptor() ([]byte, []int) {
	return file_functional_v1_complex_proto_rawDescGZIP(), []int{2}
}

func (x *ComplexRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *ComplexRequest) GetMetadata() *ComplexMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ComplexRequest) GetTargets() []*ComplexTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ComplexRequest) GetTargetByKey() map[string]*ComplexTarget {
	if x != nil {
		return x.TargetByKey
	}
	return nil
}

func (x *ComplexRequest) GetMetadataByKey() map[string]*ComplexMetadata {
	if x != nil {
		return x.MetadataByKey
	}
	return nil
}

func (x *ComplexRequest) GetPriorities() []Priority {
	if x != nil {
		return x.Priorities
	}
	return nil
}

var File_functional_v1_complex_proto protoreflect.FileDescriptor

const file_functional_v1_complex_proto_rawDesc = "" +
	"\n" +
	"\x1bfunctional/v1/complex.proto\x12\rfunctional.v1\"=\n" +
	"\x0fComplexMetadata\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"[\n" +
	"\rComplexTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1e.functional.v1.ComplexMetadataR\bmetadata\"\xe0\x04\n" +
	"\x0eComplexRequest\x123\n" +
	"\bpriority\x18\x01 \x01(\x0e2\x17.functional.v1.PriorityR\bpriority\x12:\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1e.functional.v1.ComplexMetadataR\bmetadata\x126\n" +
	"\atargets\x18\x03 \x03(\v2\x1c.functional.v1.ComplexTargetR\atargets\x12R\n" +
	"\rtarget_by_key\x18\x04 \x03(\v2..functional.v1.ComplexRequest.TargetByKeyEntryR\vtargetByKey\x12X\n" +
	"\x0fmetadata_by_key\x18\x05 \x03(\v20.functional.v1.ComplexRequest.MetadataByKeyEntryR\rmetadataByKey\x127\n" +
	"\n" +
	"priorities\x18\x06 \x03(\x0e2\x17.functional.v1.PriorityR\n" +
	"priorities\x1a\\\n" +
	"\x10TargetByKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.functional.v1.ComplexTargetR\x05value:\x028\x01\x1a`\n" +
	"\x12MetadataByKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.functional.v1.ComplexMetadataR\x05value:\x028\x01*I\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x02B8Z6go.cadenya.com/mcp-grpc-gateway/internal/testpb;testpbb\x06proto3"

var (
	file_functional_v1_complex_proto_rawDescOnce sync.Once
	file_functional_v1_complex_proto_rawDescData []byte
)

func file_functional_v1_complex_proto_rawDescGZIP() []byte {
	file_functional_v1_complex_proto_rawDescOnce.Do(func() {
		file_functional_v1_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_functional_v1_complex_proto_rawDesc), len(file_functional_v1_complex_proto_rawDesc)))
	})
	return file_functional_v1_complex_proto_rawDescData
}

var file_functional_v1_complex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_functional_v1_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_functional_v1_complex_proto_goTypes = []any{
	(Priority)(0),           // 0: functional.v1.Priority
	(*ComplexMetadata)(nil), // 1: functional.v1.ComplexMetadata
	(*ComplexTarget)(nil),   // 2: functional.v1.ComplexTarget
	(*ComplexRequest)(nil),  // 3: functional.v1.ComplexRequest
	nil,                     // 4: functional.v1.ComplexRequest.TargetByKeyEntry
	nil,                     // 5: functional.v1.ComplexRequest.MetadataByKeyEntry
}
var file_functional_v1_complex_proto_depIdxs = []int32{
	1, // 0: functional.v1.ComplexTarget.metadata:type_name -> functional.v1.ComplexMetadata
	0, // 1: functional.v1.ComplexRequest.priority:type_name -> functional.v1.Priority
	1, // 2: functional.v1.ComplexRequest.metadata:type_name -> functional.v1.ComplexMetadata
	2, // 3: functional.v1.ComplexRequest.targets:type_name -> functional.v1.ComplexTarget
	4, // 4: functional.v1.ComplexRequest.target_by_key:type_name -> functional.v1.ComplexRequest.TargetByKeyEntry
	5, // 5: functional.v1.ComplexRequest.metadata_by_key:type_name -> functional.v1.ComplexRequest.MetadataByKeyEntry
	0, // 6: functional.v1.ComplexRequest.priorities:type_name -> functional.v1.Priority
	2, // 7: functional.v1.ComplexRequest.TargetByKeyEntry.value:type_name -> functional.v1.ComplexTarget
	1, // 8: functional.v1.ComplexRequest.MetadataByKeyEntry.value:type_name -> functional.v1.ComplexMetadata
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_functional_v1_complex_proto_init() }
func file_functional_v1_complex_proto_init() {
	if File_functional_v1_complex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_functional_v1_complex_proto_rawDesc), len(file_functional_v1_complex_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_functional_v1_complex_proto_goTypes,
		DependencyIndexes: file_functional_v1_complex_proto_depIdxs,
		EnumInfos:         file_functional_v1_complex_proto_enumTypes,
		MessageInfos:      file_functional_v1_complex_proto_msgTypes,
	}.Build()
	File_functional_v1_complex_proto = out.File
	file_functional_v1_complex_proto_goTypes = nil
	file_functional_v1_complex_proto_depIdxs = nil
}
