// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: functional/v1/greeter.proto

package testpb

import (
	_ "go.cadenya.com/mcp-grpc-gateway/gen/grpcmcpgateway/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_functional_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_functional_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_functional_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_functional_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type WatchGreetingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGreetingsRequest) Reset() {
	*x = WatchGreetingsRequest{}
	mi := &file_functional_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGreetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGreetingsRequest) ProtoMessage() {}

func (x *WatchGreetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGreetingsRequest.ProtoReflect.Descriptor instead.
func (*WatchGreetingsRequest) Descriptor() ([]byte, []int) {
	return file_functional_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *WatchGreetingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchGreetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGreetingsResponse) Reset() {
	*x = WatchGreetingsResponse{}
	mi := &file_functional_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGreetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGreetingsResponse) ProtoMessage() {}

func (x *WatchGreetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_functional_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGreetingsResponse.ProtoReflect.Descriptor instead.
func (*WatchGreetingsResponse) Descriptor() ([]byte, []int) {
	return file_functional_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *WatchGreetingsResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_functional_v1_greeter_proto protoreflect.FileDescriptor

const file_functional_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bfunctional/v1/greeter.proto\x12\rfunctional.v1\x1a#grpcmcpgateway/v1/annotations.proto\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\rGreetResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"+\n" +
	"\x15WatchGreetingsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x16WatchGreetingsResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting2\xde\x01\n" +
	"\x0eGreeterService\x12k\n" +
	"\x05Greet\x12\x1b.functional.v1.GreetRequest\x1a\x1c.functional.v1.GreetResponse\"'\xa2\x8d'#\n" +
	"\n" +
	"greet_user\x12\x15Greets a user by name\x12_\n" +
	"\x0eWatchGreetings\x12$.functional.v1.WatchGreetingsRequest\x1a%.functional.v1.WatchGreetingsResponse0\x01B8Z6go.cadenya.com/mcp-grpc-gateway/internal/testpb;testpbb\x06proto3"

var (
	file_functional_v1_greeter_proto_rawDescOnce sync.Once
	file_functional_v1_greeter_proto_rawDescData []byte
)

func file_functional_v1_greeter_proto_rawDescGZIP() []byte {
	file_functional_v1_greeter_proto_rawDescOnce.Do(func() {
		file_functional_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_functional_v1_greeter_proto_rawDesc), len(file_functional_v1_greeter_proto_rawDesc)))
	})
	return file_functional_v1_greeter_proto_rawDescData
}

var file_functional_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_functional_v1_greeter_proto_goTypes = []any{
	(*GreetRequest)(nil),           // 0: functional.v1.GreetRequest
	(*GreetResponse)(nil),          // 1: functional.v1.GreetResponse
	(*WatchGreetingsRequest)(nil),  // 2: functional.v1.WatchGreetingsRequest
	(*WatchGreetingsResponse)(nil), // 3: functional.v1.WatchGreetingsResponse
}
var file_functional_v1_greeter_proto_depIdxs = []int32{
	0, // 0: functional.v1.GreeterService.Greet:input_type -> functional.v1.GreetRequest
	2, // 1: functional.v1.GreeterService.WatchGreetings:input_type -> functional.v1.WatchGreetingsRequest
	1, // 2: functional.v1.GreeterService.Greet:output_type -> functional.v1.GreetResponse
	3, // 3: functional.v1.GreeterService.WatchGreetings:output_type -> functional.v1.WatchGreetingsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_functional_v1_greeter_proto_init() }
func file_functional_v1_greeter_proto_init() {
	if File_functional_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_functional_v1_greeter_proto_rawDesc), len(file_functional_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_functional_v1_greeter_proto_goTypes,
		DependencyIndexes: file_functional_v1_greeter_proto_depIdxs,
		MessageInfos:      file_functional_v1_greeter_proto_msgTypes,
	}.Build()
	File_functional_v1_greeter_proto = out.File
	file_functional_v1_greeter_proto_goTypes = nil
	file_functional_v1_greeter_proto_depIdxs = nil
}
