// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/faker/v1/faker.proto

package fakerpb

import (
	_ "go.cadenya.com/mcp-grpc-gateway/gen/grpcmcpgateway/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFakerOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFakerOptionsRequest) Reset() {
	*x = GetFakerOptionsRequest{}
	mi := &file_examples_faker_v1_faker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFakerOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFakerOptionsRequest) ProtoMessage() {}

func (x *GetFakerOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_faker_v1_faker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFakerOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetFakerOptionsRequest) Descriptor() ([]byte, []int) {
	return file_examples_faker_v1_faker_proto_rawDescGZIP(), []int{0}
}

func (x *GetFakerOptionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type FakerOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Arguments     []*FakerArgument       `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakerOption) Reset() {
	*x = FakerOption{}
	mi := &file_examples_faker_v1_faker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakerOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakerOption) ProtoMessage() {}

func (x *FakerOption) ProtoReflect() protoreflect.Message {
	mi := &file_examples_faker_v1_faker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakerOption.ProtoReflect.Descriptor instead.
func (*FakerOption) Descriptor() ([]byte, []int) {
	return file_examples_faker_v1_faker_proto_rawDescGZIP(), []int{1}
}

func (x *FakerOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FakerOption) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FakerOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FakerOption) GetArguments() []*FakerArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type FakerArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Default       *structpb.Value        `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakerArgument) Reset() {
	*x = FakerArgument{}
	mi := &file_examples_faker_v1_faker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakerArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakerArgument) ProtoMessage() {}

func (x *FakerArgument) ProtoReflect() protoreflect.Message {
	mi := &file_examples_faker_v1_faker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakerArgument.ProtoReflect.Descriptor instead.
func (*FakerArgument) Descriptor() ([]byte, []int) {
	return file_examples_faker_v1_faker_proto_rawDescGZIP(), []int{2}
}

func (x *FakerArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FakerArgument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FakerArgument) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FakerArgument) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

type GetFakerOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*FakerOption         `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFakerOptionsResponse) Reset() {
	*x = GetFakerOptionsResponse{}
	mi := &file_examples_faker_v1_faker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFakerOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFakerOptionsResponse) ProtoMessage() {}

func (x *GetFakerOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_faker_v1_faker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFakerOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetFakerOptionsResponse) Descriptor() ([]byte, []int) {
	return file_examples_faker_v1_faker_proto_rawDescGZIP(), []int{3}
}

func (x *GetFakerOptionsResponse) GetOptions() []*FakerOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type GenerateFakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          *structpb.Struct       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFakeRequest) Reset() {
	*x = GenerateFakeRequest{}
	mi := &file_examples_faker_v1_faker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFakeRequest) ProtoMessage() {}

func (x *GenerateFakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_faker_v1_faker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFakeRequest.ProtoReflect.Descriptor instead.
func (*GenerateFakeRequest) Descriptor() ([]byte, []int) {
	return file_examples_faker_v1_faker_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateFakeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateFakeRequest) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type GenerateFakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFakeResponse) Reset() {
	*x = GenerateFakeResponse{}
	mi := &file_examples_faker_v1_faker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFakeResponse) ProtoMessage() {}

func (x *GenerateFakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_faker_v1_faker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFakeResponse.ProtoReflect.Descriptor instead.
func (*GenerateFakeResponse) Descriptor() ([]byte, []int) {
	return file_examples_faker_v1_faker_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateFakeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateFakeResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_examples_faker_v1_faker_proto protoreflect.FileDescriptor

const file_examples_faker_v1_faker_proto_rawDesc = "" +
	"\n" +
	"\x1dexamples/faker/v1/faker.proto\x12\x11examples.faker.v1\x1a#grpcmcpgateway/v1/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"0\n" +
	"\x16GetFakerOptionsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"\x9f\x01\n" +
	"\vFakerOption\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12>\n" +
	"\targuments\x18\x04 \x03(\v2 .examples.faker.v1.FakerArgumentR\targuments\"\x8b\x01\n" +
	"\rFakerArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\adefault\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\adefault\"S\n" +
	"\x17GetFakerOptionsResponse\x128\n" +
	"\aoptions\x18\x01 \x03(\v2\x1e.examples.faker.v1.FakerOptionR\aoptions\"V\n" +
	"\x13GenerateFakeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\"@\n" +
	"\x14GenerateFakeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xa2\x03\n" +
	"\fFakerService\x12\xe6\x01\n" +
	"\x0fGetFakerOptions\x12).examples.faker.v1.GetFakerOptionsRequest\x1a*.examples.faker.v1.GetFakerOptionsResponse\"|\xa2\x8d'x\n" +
	"\x0fGetFakerOptions\x12eLists supported fake data generators. Use filter to narrow options by name, category, or description.\x12\xa8\x01\n" +
	"\fGenerateFake\x12&.examples.faker.v1.GenerateFakeRequest\x1a'.examples.faker.v1.GenerateFakeResponse\"G\xa2\x8d'C\n" +
	"\fGenerateFake\x123Generates one fake data value by faker option name.B@Z>go.cadenya.com/mcp-grpc-gateway/examples/faker/fakerpb;fakerpbb\x06proto3"

var (
	file_examples_faker_v1_faker_proto_rawDescOnce sync.Once
	file_examples_faker_v1_faker_proto_rawDescData []byte
)

func file_examples_faker_v1_faker_proto_rawDescGZIP() []byte {
	file_examples_faker_v1_faker_proto_rawDescOnce.Do(func() {
		file_examples_faker_v1_faker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_faker_v1_faker_proto_rawDesc), len(file_examples_faker_v1_faker_proto_rawDesc)))
	})
	return file_examples_faker_v1_faker_proto_rawDescData
}

var file_examples_faker_v1_faker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_examples_faker_v1_faker_proto_goTypes = []any{
	(*GetFakerOptionsRequest)(nil),  // 0: examples.faker.v1.GetFakerOptionsRequest
	(*FakerOption)(nil),             // 1: examples.faker.v1.FakerOption
	(*FakerArgument)(nil),           // 2: examples.faker.v1.FakerArgument
	(*GetFakerOptionsResponse)(nil), // 3: examples.faker.v1.GetFakerOptionsResponse
	(*GenerateFakeRequest)(nil),     // 4: examples.faker.v1.GenerateFakeRequest
	(*GenerateFakeResponse)(nil),    // 5: examples.faker.v1.GenerateFakeResponse
	(*structpb.Value)(nil),          // 6: google.protobuf.Value
	(*structpb.Struct)(nil),         // 7: google.protobuf.Struct
}
var file_examples_faker_v1_faker_proto_depIdxs = []int32{
	2, // 0: examples.faker.v1.FakerOption.arguments:type_name -> examples.faker.v1.FakerArgument
	6, // 1: examples.faker.v1.FakerArgument.default:type_name -> google.protobuf.Value
	1, // 2: examples.faker.v1.GetFakerOptionsResponse.options:type_name -> examples.faker.v1.FakerOption
	7, // 3: examples.faker.v1.GenerateFakeRequest.args:type_name -> google.protobuf.Struct
	0, // 4: examples.faker.v1.FakerService.GetFakerOptions:input_type -> examples.faker.v1.GetFakerOptionsRequest
	4, // 5: examples.faker.v1.FakerService.GenerateFake:input_type -> examples.faker.v1.GenerateFakeRequest
	3, // 6: examples.faker.v1.FakerService.GetFakerOptions:output_type -> examples.faker.v1.GetFakerOptionsResponse
	5, // 7: examples.faker.v1.FakerService.GenerateFake:output_type -> examples.faker.v1.GenerateFakeResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_examples_faker_v1_faker_proto_init() }
func file_examples_faker_v1_faker_proto_init() {
	if File_examples_faker_v1_faker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_faker_v1_faker_proto_rawDesc), len(file_examples_faker_v1_faker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_faker_v1_faker_proto_goTypes,
		DependencyIndexes: file_examples_faker_v1_faker_proto_depIdxs,
		MessageInfos:      file_examples_faker_v1_faker_proto_msgTypes,
	}.Build()
	File_examples_faker_v1_faker_proto = out.File
	file_examples_faker_v1_faker_proto_goTypes = nil
	file_examples_faker_v1_faker_proto_depIdxs = nil
}
