// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: examples/faker/v1/faker.proto

package fakerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FakerService_GetFakerOptions_FullMethodName = "/examples.faker.v1.FakerService/GetFakerOptions"
	FakerService_GenerateFake_FullMethodName    = "/examples.faker.v1.FakerService/GenerateFake"
)

// FakerServiceClient is the client API for FakerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FakerServiceClient interface {
	GetFakerOptions(ctx context.Context, in *GetFakerOptionsRequest, opts ...grpc.CallOption) (*GetFakerOptionsResponse, error)
	GenerateFake(ctx context.Context, in *GenerateFakeRequest, opts ...grpc.CallOption) (*GenerateFakeResponse, error)
}

type fakerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFakerServiceClient(cc grpc.ClientConnInterface) FakerServiceClient {
	return &fakerServiceClient{cc}
}

func (c *fakerServiceClient) GetFakerOptions(ctx context.Context, in *GetFakerOptionsRequest, opts ...grpc.CallOption) (*GetFakerOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFakerOptionsResponse)
	err := c.cc.Invoke(ctx, FakerService_GetFakerOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fakerServiceClient) GenerateFake(ctx context.Context, in *GenerateFakeRequest, opts ...grpc.CallOption) (*GenerateFakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateFakeResponse)
	err := c.cc.Invoke(ctx, FakerService_GenerateFake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FakerServiceServer is the server API for FakerService service.
// All implementations must embed UnimplementedFakerServiceServer
// for forward compatibility.
type FakerServiceServer interface {
	GetFakerOptions(context.Context, *GetFakerOptionsRequest) (*GetFakerOptionsResponse, error)
	GenerateFake(context.Context, *GenerateFakeRequest) (*GenerateFakeResponse, error)
	mustEmbedUnimplementedFakerServiceServer()
}

// UnimplementedFakerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFakerServiceServer struct{}

func (UnimplementedFakerServiceServer) GetFakerOptions(context.Context, *GetFakerOptionsRequest) (*GetFakerOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFakerOptions not implemented")
}
func (UnimplementedFakerServiceServer) GenerateFake(context.Context, *GenerateFakeRequest) (*GenerateFakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateFake not implemented")
}
func (UnimplementedFakerServiceServer) mustEmbedUnimplementedFakerServiceServer() {}
func (UnimplementedFakerServiceServer) testEmbeddedByValue()                      {}

// UnsafeFakerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FakerServiceServer will
// result in compilation errors.
type UnsafeFakerServiceServer interface {
	mustEmbedUnimplementedFakerServiceServer()
}

func RegisterFakerServiceServer(s grpc.ServiceRegistrar, srv FakerServiceServer) {
	// If the following call panics, it indicates UnimplementedFakerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FakerService_ServiceDesc, srv)
}

func _FakerService_GetFakerOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFakerOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FakerServiceServer).GetFakerOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FakerService_GetFakerOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FakerServiceServer).GetFakerOptions(ctx, req.(*GetFakerOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FakerService_GenerateFake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateFakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FakerServiceServer).GenerateFake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FakerService_GenerateFake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FakerServiceServer).GenerateFake(ctx, req.(*GenerateFakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FakerService_ServiceDesc is the grpc.ServiceDesc for FakerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FakerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "examples.faker.v1.FakerService",
	HandlerType: (*FakerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFakerOptions",
			Handler:    _FakerService_GetFakerOptions_Handler,
		},
		{
			MethodName: "GenerateFake",
			Handler:    _FakerService_GenerateFake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/faker/v1/faker.proto",
}
